#!/bin/bash

# Load environment variables from .env file
if [ -f .env ]; then
    export $(grep -v '^#' .env | xargs)
fi

# Set environment variables
export GOOGLE_LOGGING_PROJECT_ID=${GOOGLE_LOGGING_PROJECT_ID}
export GOOGLE_LOGGING_LOG_NAME=${GOOGLE_LOGGING_LOG_NAME}
export GEMINI_PROJECT_ID=${GEMINI_PROJECT_ID}
export GEMINI_LOCATION=${GEMINI_LOCATION}
export GEMINI_MODEL=${GEMINI_MODEL}
export GEMINI_TOKEN_LIMIT=${GEMINI_TOKEN_LIMIT}
export GEMINI_TEMPERATURE=${GEMINI_TEMPERATURE}
export GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}

export OPENAI_API_KEY=${OPENAI_API_KEY}
export OPENAI_MODEL=${OPENAI_MODEL}
export ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
export ANTHROPIC_MODEL=${ANTHROPIC_MODEL}

export GROQ_API_KEY=${GROQ_API_KEY}
export GROQ_MODEL=${GROQ_MODEL}

export LAMBDA_LAB_API_KEY=${LAMBDA_LAB_API_KEY}
export LAMBDA_LAB_MODEL=${LAMBDA_LAB_MODEL}

export GEMINI_API_KEY=${GEMINI_API_KEY}

go test -v ./...
