#!/bin/bash

# Load environment variables from .env file
if [ -f .env ]; then
    export $(grep -v '^#' .env | xargs)
fi

# Set environment variables
export GOOGLE_LOGGING_PROJECT_ID=${GOOGLE_LOGGING_PROJECT_ID}
export GOOGLE_LOGGING_LOG_NAME=${GOOGLE_LOGGING_LOG_NAME}
export GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}
export GOOGLE_LOCATION=${GOOGLE_LOCATION}
export GOOGLE_MODEL=${GOOGLE_MODEL}
export GOOGLE_TOKEN_LIMIT=${GOOGLE_TOKEN_LIMIT}
export GOOGLE_TEMPERATURE=${GOOGLE_TEMPERATURE}
export GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}

export OPENAI_API_KEY=${OPENAI_API_KEY}
export OPENAI_MODEL=${OPENAI_MODEL}
export ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
export ANTHROPIC_MODEL=${ANTHROPIC_MODEL}

export GROQ_API_KEY=${GROQ_API_KEY}
export GROQ_MODEL=${GROQ_MODEL}

export LAMBDA_LAB_API_KEY=${LAMBDA_LAB_API_KEY}
export LAMBDA_LAB_MODEL=${LAMBDA_LAB_MODEL}

export GEMINI_API_KEY=${GEMINI_API_KEY}

go test -v ./...
